---

- name: get list of zones
  uri:
    url: "{{ base_address }}/api/zones/list?token={{ dns_configurations.token }}"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: zones_list_response

- name: get current records in each zone
  uri:
    url: "{{ base_address }}/api/zones/records/get?token={{ dns_configurations.token }}&domain={{ item.name }}&listZone=true"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  when: item.type == "Primary" and item.internal == false
  loop: "{{ zones_list_response.json.response.zones }}"
  register: list_records_response

- name: Display DNS records for each zone
  debug:
    var: list_records_response

